name: "release"
run-name: "v${{ inputs.version }}"

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "App version (x.y.z)"
        required: true
      release_tag:
        type: string
        description: "Release tag (default: <version>)"
        required: false
        # default: "__VERSION__"
      release_name:
        type: string
        description: "Release name"
        required: true
        default: "App v__VERSION__"
      is_draft:
        type: boolean
        description: "Save as Draft"
        required: true
        default: true
      prerelease:
        type: boolean
        description: "Pre-release"
        required: false
        default: false
      enable_sourcemap:
        type: boolean
        description: "Enable sourcemap"
        required: false
        default: false
      delete_release:
        type: boolean
        description: "Delete duplicate release"
        required: false
        default: false

jobs:
  build:
    permissions:
      contents: write
    uses: ./.github/workflows/publish.yml
    with:
      app_version: ${{ inputs.version }}
      release_tag: ${{ inputs.release_tag != '' && inputs.release_tag || inputs.version }}
      release_name: ${{ inputs.release_name }}
      is_draft: ${{ inputs.is_draft }}
      prerelease: ${{ inputs.prerelease }}
      enable_sourcemap: ${{ inputs.enable_sourcemap }}
      delete_release: ${{ inputs.delete_release }}
    # secrets:
      